module.exports = function(dom) {
  // Remove the generated time that LaTeXML adds, because this is non-deterministic for tests
  const logo = dom.querySelector(".ltx_page_logo");
  logo.innerHTML = `Generated by <a href="http://dlmf.nist.gov/LaTeXML/">LaTeXML</a>`;
};
